### 1. Menambah Data Mutiara Adinda
POST http://localhost:3000/mahasiswa
Content-Type: application/json

{
    "nim": "241572010005",
    "nama": "Mutiara Adinda"
}

### ---------------------------------------------------------

### 2. Melihat Daftar Mahasiswa (Untuk Cek Apakah Sudah Masuk)
GET http://localhost:3000/mahasiswa

### Input Skor Mutabaah untuk Mutiara (ID: 1)
POST http://localhost:3000/mutabaah
Content-Type: application/json

{
    "mahasiswa_id": 1,
    "tanggal": "2025-12-23",
    "shalat_5_waktu": 100,
    "tilawah_halaman": 10
}